exchange:
  name: "whitebit"
  api_key: "${WB_API_KEY}"
  secret: "${WB_SECRET}"
  sandbox: false
lunarcrush:
  api_key: "${LC_API_KEY}"
strategies:
  rsi_period: 14
  galaxy_score_threshold: 70
risk:
  max_position_size: 0.05
  stop_loss: 0.02
  take_profit: 0.04
